import { readFileSync } from 'node:fs';
import type { TelemetryInput } from '../../src/types.js';

let cachedTelemetry: TelemetryInput | null = null;

/**
 * SYNTHETIC. Generated by generate-telemetry.mjs beside it — see that file for the cases it
 * encodes. Regenerate after any change to the session shape.
 */
export function sampleTelemetry(): TelemetryInput {
    if (!cachedTelemetry) {
        const raw = readFileSync(new URL('./telemetry-sessions.json', import.meta.url), 'utf8');
        cachedTelemetry = JSON.parse(raw) as TelemetryInput;
    }
    return cachedTelemetry;
}

export const FIXTURE_REPO = 'Bellows-AI/bellows.ai';

/** The window the fixture was generated in, so `partial` week flags stay stable. */
export const FIXTURE_NOW = new Date('2026-08-21T12:00:00.000Z');
