-- The organization dimension.
--
-- An organization owns a set of repos and partitions all stored history. There is exactly one per
-- deployment today, defined in the environment (ORG_ID/ORG_NAME), with no accounts and no memberships — but org_id is
-- folded into the primary keys NOW, while the tables are small, rather than retrofitted later
-- across ten keys, four foreign keys and six indexes on a populated database.
--
-- `org_id` LEADS every key rather than trailing `provider`. A query always knows its org — it is a
-- constant for the life of the process today and a request-scoped value tomorrow — so leading it
-- makes every index a prefix scan of the partition rather than a filter applied after the fact.
--
-- WHICH TABLES: exactly those that already carry `repo`. That is not a coincidence. A repo belongs
-- to an organization, so anything keyed by repo is keyed by organization.
--
-- metric_point is the deliberate exception, and it must stay one. It carries no `repo` either (see
-- the comment in 001_init.sql: "the repo is resolved by joining to session_branch, so there is one
-- source of truth rather than two that disagree"), so its organization comes through that same
-- join. Adding the column would mean a second source of truth for one fact AND rebuilding a unique
-- index on a hypertable, bought for nothing. Consequence worth knowing: a session with metrics but
-- no session_branch row belongs to no organization at all. With one organization that is
-- invisible; with several it is honestly unattributable, which is already how sessionsWithoutHook
-- reports it.
--
-- WHY '__unclaimed__' AND NOT THE CONFIGURED ID: this file cannot see the config, and guessing
-- wrong is silent. Backfilling the literal 'default' would leave a deployment that sets
-- ORG_ID=bellows pointed at an empty partition: 200 OK, zero PRs, no log line, indistinguishable
-- from data loss. Instead every pre-organization row is parked in a reserved namespace and adopted
-- into the configured org exactly once, by adoptOrg() in db/migrate.ts. config.ts refuses any id
-- beginning with '__' so the namespace cannot be squatted.
--
-- This file must contain NO `create extension` and NO `create_hypertable`. Those misbehave inside a
-- transaction, and without them postgres wraps the whole multi-statement body in an implicit one —
-- which is what makes ten key rewrites atomic, so a crashed run rolls back whole instead of
-- leaving half a schema behind.

-- 1. The column. Reserved placeholder, adopted at boot.
alter table pull_request     add column if not exists org_id text not null default '__unclaimed__';
alter table pr_review        add column if not exists org_id text not null default '__unclaimed__';
alter table pr_review_thread add column if not exists org_id text not null default '__unclaimed__';
alter table pr_commit        add column if not exists org_id text not null default '__unclaimed__';
alter table pr_label         add column if not exists org_id text not null default '__unclaimed__';
alter table branch_commit    add column if not exists org_id text not null default '__unclaimed__';
alter table branch_history   add column if not exists org_id text not null default '__unclaimed__';
alter table sync_state       add column if not exists org_id text not null default '__unclaimed__';
alter table session_branch   add column if not exists org_id text not null default '__unclaimed__';
alter table session_pr       add column if not exists org_id text not null default '__unclaimed__';

-- 2. Drop the foreign keys pointing at pull_request before its primary key can move. Their names
--    were auto-generated by 004, so they are looked up rather than assumed — a hardcoded
--    `pr_review_provider_repo_pr_number_fkey` is a guess that fails only on someone else's
--    database.
do $$
declare c record;
begin
    for c in select conname, conrelid::regclass as tbl
             from pg_constraint
             where contype = 'f' and confrelid = 'pull_request'::regclass
    loop
        execute format('alter table %s drop constraint %I', c.tbl, c.conname);
    end loop;
end $$;

-- 3. Rekey. Every constraint is given an EXPLICIT name, so the next migration to touch one can
--    name it instead of querying the catalogue for whatever postgres happened to call it.
alter table pull_request drop constraint if exists pull_request_pkey;
alter table pull_request add constraint pull_request_pk
    primary key (org_id, provider, repo, number);

alter table pr_review drop constraint if exists pr_review_pkey;
alter table pr_review add constraint pr_review_pk
    primary key (org_id, provider, repo, pr_number, review_key);

alter table pr_review_thread drop constraint if exists pr_review_thread_pkey;
alter table pr_review_thread add constraint pr_review_thread_pk
    primary key (org_id, provider, repo, pr_number, thread_key);

alter table pr_commit drop constraint if exists pr_commit_pkey;
alter table pr_commit add constraint pr_commit_pk
    primary key (org_id, provider, repo, pr_number, sha);

alter table pr_label drop constraint if exists pr_label_pkey;
alter table pr_label add constraint pr_label_pk
    primary key (org_id, provider, repo, pr_number, label);

alter table branch_commit drop constraint if exists branch_commit_pkey;
alter table branch_commit add constraint branch_commit_pk
    primary key (org_id, provider, repo, branch, sha);

alter table branch_history drop constraint if exists branch_history_pkey;
alter table branch_history add constraint branch_history_pk
    primary key (org_id, provider, repo, branch);

alter table sync_state drop constraint if exists sync_state_pkey;
alter table sync_state add constraint sync_state_pk
    primary key (org_id, provider, repo, kind);

-- `branch` is declared nullable in 001_init.sql with the comment "null on detached HEAD", but it
-- sits in this primary key, so postgres rejects exactly those rows — and has since 001. That is a
-- pre-existing bug, preserved here deliberately rather than fixed in passing: the repair is a
-- unique index over `coalesce(branch, '')`, which changes the `on conflict` target in three
-- separate write paths and does not deserve review alongside eleven key rewrites.
alter table session_branch drop constraint if exists session_branch_pkey;
alter table session_branch add constraint session_branch_pk
    primary key (org_id, agent, session_id, repo, branch);

alter table session_pr drop constraint if exists session_pr_pkey;
alter table session_pr add constraint session_pr_pk
    primary key (org_id, agent, session_id, repo, pr_number);

-- 4. The foreign keys again, org included, delete-cascade preserved. Without org_id in the
--    reference a child row could point at a parent in another organization.
--
--    ON UPDATE CASCADE is new, and it is what makes adoptOrg() in db/migrate.ts possible at all.
--    org_id is now part of the reference, so moving a parent out of the '__unclaimed__' namespace
--    is an update to a referenced key. Without the cascade there is no legal order to do it in:
--    children first orphans them mid-statement, parents first strands the children. With it,
--    adoptOrg updates pull_request alone and the four child tables follow atomically.
--
--    Nothing in the write path ever updates org_id, so this fires exactly once per database.
alter table pr_review add constraint pr_review_pr_fk
    foreign key (org_id, provider, repo, pr_number)
    references pull_request (org_id, provider, repo, number)
    on update cascade on delete cascade;

alter table pr_review_thread add constraint pr_review_thread_pr_fk
    foreign key (org_id, provider, repo, pr_number)
    references pull_request (org_id, provider, repo, number)
    on update cascade on delete cascade;

alter table pr_commit add constraint pr_commit_pr_fk
    foreign key (org_id, provider, repo, pr_number)
    references pull_request (org_id, provider, repo, number)
    on update cascade on delete cascade;

alter table pr_label add constraint pr_label_pr_fk
    foreign key (org_id, provider, repo, pr_number)
    references pull_request (org_id, provider, repo, number)
    on update cascade on delete cascade;

-- 5. Indexes, org leading. Dropped and recreated rather than left in place: an index that does not
--    lead with the partition is a scan of every organization's rows followed by a filter.
--
--    metric_point's two indexes are untouched, per the header.

-- THE read-path index. `stats.meta.window` is derived from array position, so the store has to
-- reproduce the ordering the GraphQL query used to provide, and this is what keeps
-- `order by created_at desc` an index scan rather than a sort of every row.
drop index if exists pull_request_repo_created;
create index if not exists pull_request_repo_created
    on pull_request (org_id, provider, repo, created_at desc);

drop index if exists pull_request_repo_updated;
create index if not exists pull_request_repo_updated
    on pull_request (org_id, provider, repo, provider_updated_at desc);

-- Still partial: the cutoff floor for an incremental sync reads the oldest still-open PR.
drop index if exists pull_request_open_updated;
create index if not exists pull_request_open_updated
    on pull_request (org_id, provider, repo, provider_updated_at)
    where state = 'open';

drop index if exists branch_commit_branch;
create index if not exists branch_commit_branch
    on branch_commit (org_id, provider, repo, branch, committed_at desc);

drop index if exists session_branch_repo;
create index if not exists session_branch_repo
    on session_branch (org_id, repo, branch);

drop index if exists session_pr_repo;
create index if not exists session_pr_repo
    on session_pr (org_id, repo, pr_number);
